# Generated by Django 5.0.1 on 2024-02-18 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_factory_customuser_role_customuser_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subordinates',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
