# Generated by Django 5.0.1 on 2024-02-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('waits', 'Ожидает'), ('runs', 'В работе'), ('done', 'Выполено')], default='waits', max_length=20),
        ),
    ]
